// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NtM6GCCMKdteo2XpA_MRduB2wa_OT8A',
    appId: '1:396697033327:web:ae28357e6daf2eb5a34b9a',
    messagingSenderId: '396697033327',
    projectId: 'prototyp-2022',
    authDomain: 'prototyp-2022.firebaseapp.com',
    storageBucket: 'prototyp-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOaidavQatvT7DIm-XzxddOBpQNM8vtaY',
    appId: '1:396697033327:android:ad7bf3ff951dfd03a34b9a',
    messagingSenderId: '396697033327',
    projectId: 'prototyp-2022',
    storageBucket: 'prototyp-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrBe3N69NMEaHF2sdznkyjmOPPd8t5ak',
    appId: '1:396697033327:ios:b5c299c861e82425a34b9a',
    messagingSenderId: '396697033327',
    projectId: 'prototyp-2022',
    storageBucket: 'prototyp-2022.appspot.com',
    iosClientId: '396697033327-p7a8pm8ohn8aeplretmgigu1e8root8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototypFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrBe3N69NMEaHF2sdznkyjmOPPd8t5ak',
    appId: '1:396697033327:ios:b5c299c861e82425a34b9a',
    messagingSenderId: '396697033327',
    projectId: 'prototyp-2022',
    storageBucket: 'prototyp-2022.appspot.com',
    iosClientId: '396697033327-p7a8pm8ohn8aeplretmgigu1e8root8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototypFlutter',
  );
}
